# Generated by Django 5.2.16 on 2026-07-29 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'RFQ reference counter',
            },
        ),
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('county', models.CharField(max_length=60)),
                ('town', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, help_text='Building, street or estate.', max_length=200)),
                ('project_type', models.CharField(blank=True, max_length=60)),
                ('service_required', models.CharField(max_length=120)),
                ('equipment', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, help_text='Optional plans/photos from the customer.', upload_to='rfq/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('survey_scheduled', 'Site Survey Scheduled'), ('quotation_sent', 'Quotation Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('closed', 'Closed')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website form'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone call'), ('email', 'Email'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='website', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Never shown to the customer.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigned engineer')),
            ],
            options={
                'verbose_name': 'Quotation request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.quotationrequest')),
            ],
            options={
                'verbose_name_plural': 'Lead activities',
                'ordering': ['-at'],
            },
        ),
    ]
