# Generated by Django 5.2.16 on 2026-07-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='source',
            field=models.CharField(choices=[('website', 'Website form'), ('chatbot', 'Website chatbot'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone call'), ('email', 'Email'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='website', max_length=20),
        ),
    ]
