# Generated by Django 5.2.16 on 2026-07-29 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Optional. Until uploaded, the frontend renders a styled wordmark.', upload_to='brands/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=60)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='MECHPRO SOLUTIONS LTD', max_length=120)),
                ('short_name', models.CharField(default='MECHPRO', max_length=40)),
                ('tagline', models.CharField(default='Professional HVAC Solutions', max_length=120)),
                ('descriptor', models.TextField(default='Kenyan mechanical engineering company delivering end-to-end HVAC and mechanical ventilation solutions — design, supply, installation, commissioning and maintenance.')),
                ('phone_display', models.CharField(default='+254 758 644 781', max_length=32)),
                ('whatsapp_number', models.CharField(default='254758644781', help_text='Digits only, international format, no plus sign.', max_length=20)),
                ('whatsapp_default_message', models.TextField(default='Hello MECHPRO SOLUTIONS LTD. I would like to request a quotation for your HVAC services.')),
                ('email_info', models.EmailField(default='info@mechpro.co.ke', max_length=254)),
                ('email_sales', models.EmailField(default='sales@mechpro.co.ke', max_length=254)),
                ('email_quotations', models.EmailField(default='quotations@mechpro.co.ke', max_length=254)),
                ('email_support', models.EmailField(default='support@mechpro.co.ke', max_length=254)),
                ('address', models.CharField(default='Nairobi, Kenya', max_length=200)),
                ('hours', models.CharField(default='Mon – Sat · 8:00 AM – 6:00 PM', max_length=100)),
                ('emergency_note', models.CharField(default='24/7 emergency response for contract clients', max_length=200)),
                ('map_embed_src', models.URLField(default='https://www.google.com/maps?q=Nairobi,Kenya&output=embed', help_text='Google Maps embed URL for the contact page.')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X (Twitter) URL')),
                ('service_areas', models.TextField(default='Nairobi, Kiambu, Machakos, Kajiado, Nakuru, Eldoret, Kisumu, Mombasa, Nyeri, Thika, Meru', help_text='Comma-separated list of counties/towns served.')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. "240+", "98%", "24/7"', max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(help_text='e.g. "Facility Manager, Westlands office park"', max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('engineer', 'Engineer'), ('leaf', 'Leaf / efficiency'), ('shield', 'Shield / warranty'), ('wrench', 'Wrench / installation'), ('clock', 'Clock / response'), ('map', 'Map / coverage'), ('bolt', 'Bolt / power'), ('check', 'Check')], default='check', max_length=20)),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why-MECHPRO item',
                'ordering': ['order', 'id'],
            },
        ),
    ]
