# Generated by Django 5.2.16 on 2026-07-29 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Product categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Browser/Google title. Leave blank to use the name/title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Google snippet text, max 160 characters.', max_length=160)),
                ('slug', models.SlugField(blank=True, help_text='URL path, e.g. lg-dualcool-12000-wall. Auto-generated if blank.', max_length=140, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('model_number', models.CharField(max_length=80)),
                ('capacity_btu', models.CharField(blank=True, help_text='e.g. "18,000". Leave blank for non-AC items.', max_length=30, verbose_name='Capacity (BTU)')),
                ('coverage', models.CharField(blank=True, help_text='e.g. "Up to 28 m²"', max_length=60)),
                ('energy_rating', models.CharField(blank=True, help_text='e.g. "A++"', max_length=30)),
                ('refrigerant', models.CharField(blank=True, help_text='e.g. "R-32"', max_length=30)),
                ('power', models.CharField(blank=True, help_text='e.g. "1.4 kW"', max_length=40)),
                ('warranty', models.CharField(blank=True, max_length=120)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings, e.g. ["Dual Inverter compressor", ...]')),
                ('ideal_for', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional (KES). Hidden from the site when blank.', max_digits=12, null=True)),
                ('brochure', models.FileField(blank=True, upload_to='brochures/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('on_promotion', models.BooleanField(default=False)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the website.')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, help_text="Incremented by the API for 'most viewed' analytics.")),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.productbrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.productcategory')),
            ],
            options={
                'ordering': ['-is_featured', 'brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, help_text='Describe the image for SEO and accessibility (WRS Image SEO).', max_length=160)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.product')),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'id'],
            },
        ),
    ]
