# Generated by Django 5.2.16 on 2026-07-29 11:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Browser/Google title. Leave blank to use the name/title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Google snippet text, max 160 characters.', max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('snowflake', 'Snowflake'), ('ruler', 'Ruler'), ('fan', 'Fan'), ('clipboard', 'Clipboard'), ('bolt', 'Bolt'), ('building', 'Building'), ('calendar', 'Calendar'), ('home', 'Home'), ('cross', 'Medical cross'), ('bed', 'Bed'), ('flame', 'Flame'), ('book', 'Book'), ('factory', 'Factory'), ('box', 'Box'), ('server', 'Server'), ('wrench', 'Wrench'), ('leaf', 'Leaf')], default='building', max_length=20)),
                ('tag', models.CharField(help_text='Short strapline, e.g. "Guest comfort, quietly"', max_length=80)),
                ('challenge', models.TextField(help_text="The sector's specific HVAC challenge.")),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Browser/Google title. Leave blank to use the name/title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Google snippet text, max 160 characters.', max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('sector', models.CharField(choices=[('Commercial', 'Commercial'), ('Hospitality', 'Hospitality'), ('Healthcare', 'Healthcare'), ('Residential', 'Residential'), ('Industrial', 'Industrial'), ('Institutional', 'Institutional')], max_length=30)),
                ('location', models.CharField(max_length=120)),
                ('year', models.CharField(max_length=10)),
                ('equipment', models.CharField(help_text='e.g. "LG Multi V VRF · 42 indoor units"', max_length=200)),
                ('summary', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Browser/Google title. Leave blank to use the name/title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Google snippet text, max 160 characters.', max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('snowflake', 'Snowflake'), ('ruler', 'Ruler'), ('fan', 'Fan'), ('clipboard', 'Clipboard'), ('bolt', 'Bolt'), ('building', 'Building'), ('calendar', 'Calendar'), ('home', 'Home'), ('cross', 'Medical cross'), ('bed', 'Bed'), ('flame', 'Flame'), ('book', 'Book'), ('factory', 'Factory'), ('box', 'Box'), ('server', 'Server'), ('wrench', 'Wrench'), ('leaf', 'Leaf')], default='snowflake', max_length=20)),
                ('plate_scope', models.CharField(help_text='e.g. "Residential – Commercial"', max_length=60, verbose_name='Spec plate — scope')),
                ('plate_lead', models.CharField(help_text='e.g. "Survey to commissioning"', max_length=60, verbose_name='Spec plate — approach')),
                ('plate_cover', models.CharField(help_text='e.g. "All major brands"', max_length=60, verbose_name='Spec plate — cover')),
                ('summary', models.TextField(help_text='Card text — one strong paragraph.')),
                ('overview', models.TextField(help_text='Detail-page opening section.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndustryApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approach_items', to='content.industry')),
            ],
            options={
                'verbose_name_plural': 'Industry approach items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Browser/Google title. Leave blank to use the name/title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Google snippet text, max 160 characters.', max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(help_text='Card/preview text — two sentences.')),
                ('body', models.TextField(help_text='Article text. Separate paragraphs with a blank line.')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Set a future date/time to schedule publication.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='content.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='content.blogtag')),
            ],
            options={
                'ordering': ['-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='content.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='content.service')),
            ],
            options={
                'verbose_name': 'Service FAQ',
                'verbose_name_plural': 'Service FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=80)),
                ('detail', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='content.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
