# Generated by Django 5.2.16 on 2026-07-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='image',
            field=models.ImageField(blank=True, help_text='Shown on the solution card and as the page banner.', upload_to='industries/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Shown on the service card and as the page banner.', upload_to='services/'),
        ),
    ]
